### ISSUE TITLE
Install Throws error

### ISSUE THREAD

**Issue by lowjumpingfrog** [jjorissen52/python-qgenda#2]
This could be my fault as I am fairly new here. But, I not sure where to go from here. When using pip install python-qgenda I get the following:

`(base) raven:T user$ pip install --upgrade setuptools
Requirement already up-to-date: setuptools in /Users/user/anaconda3/lib/python3.7/site-packages (41.0.1)`

`(base) raven:T user$ pip install ez_setup
Collecting ez_setup
  Downloading https://files.pythonhosted.org/packages/ba/2c/743df41bd6b3298706dfe91b0c7ecdc47f2dc1a3104abeb6e9aa4a45fa5d/ez_setup-0.9.tar.gz
Building wheels for collected packages: ez-setup
  Building wheel for ez-setup (setup.py) ... done
  Stored in directory: /Users/user/Library/Caches/pip/wheels/dc/e8/6b/3d5ff5a3efd7b5338d1e173ac981771e2628ceb2f7866d49ad
Successfully built ez-setup
Installing collected packages: ez-setup
Successfully installed ez-setup-0.9`

`(base) raven:T user$ pip install python-qgenda
Collecting python-qgenda
  Using cached https://files.pythonhosted.org/packages/6e/dd/bc87581eebe60bc9ebaa564691ef27c154a91986fe69220e3ac3f4235faa/python-qgenda-1.0.dev4.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/12/4_ct8hv51k5czhmwbfrpgzxh0000gn/T/pip-install-ns2gk56n/python-qgenda/setup.py", line 5, in <module>
        from qgenda import __version__
      File "/private/var/folders/12/4_ct8hv51k5czhmwbfrpgzxh0000gn/T/pip-install-ns2gk56n/python-qgenda/qgenda/__init__.py", line 3, in <module>
        from . import cache
      File "/private/var/folders/12/4_ct8hv51k5czhmwbfrpgzxh0000gn/T/pip-install-ns2gk56n/python-qgenda/qgenda/cache/__init__.py", line 1, in <module>
        from qgenda import settings
      File "/private/var/folders/12/4_ct8hv51k5czhmwbfrpgzxh0000gn/T/pip-install-ns2gk56n/python-qgenda/qgenda/settings.py", line 47, in <module>
        config_dict = read_config(DEFAULTS.keys())
      File "/private/var/folders/12/4_ct8hv51k5czhmwbfrpgzxh0000gn/T/pip-install-ns2gk56n/python-qgenda/qgenda/settings.py", line 37, in read_config
        config = configparser.ConfigParser(defaults=DEFAULTS)
      File "/Users/user/anaconda3/lib/python3.7/configparser.py", line 638, in __init__
        self._read_defaults(defaults)
      File "/Users/user/anaconda3/lib/python3.7/configparser.py", line 1216, in _read_defaults
        self.read_dict({self.default_section: defaults})
      File "/Users/user/anaconda3/lib/python3.7/configparser.py", line 753, in read_dict
        self.set(section, key, value)
      File "/Users/user/anaconda3/lib/python3.7/configparser.py", line 1197, in set
        self._validate_value_types(option=option, value=value)
      File "/Users/user/anaconda3/lib/python3.7/configparser.py", line 1182, in _validate_value_types
        raise TypeError("option values must be strings")
    TypeError: option values must be strings
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/12/4_ct8hv51k5czhmwbfrpgzxh0000gn/T/pip-install-ns2gk56n/python-qgenda/`

The configparser seems to be complaining about options not being strings. I got this after the first problem which suggested that I needed to have the QGENDA_CONF_FILE env variable set. Reading the docs it seems that this could be do during script execution. I created a conf file and set the environment variable.

I am using the last version of Anaconda on up to date MacOS. This same behavior is seen using on a machine using Linux Mint 19.1

**Comment by jjorissen52** [comment]
I believe this is due to a known issue with the version of the `configparser` library that the latest release of this project is uses. It only surfaces when with Python 3.7. 

https://github.com/ralphbean/bugwarrior/issues/597

I can do a new release to fix the issue, but it will take me a little while.

**Comment by jjorissen52** [comment]
Okay, it should work now. To re-install try

`pip install --no-cache python-qgenda`

or to explicitly target the new release

`pip install python-qgenda==1.0.dev5`

**Comment by lowjumpingfrog** [comment]
Thanks that worked. The variable from the config file go read in ok. Did you remove the argument to the configparser constructor in the read_config function in settings.py? That seemed to work when I hammered on this for a bit. Must be some other 3.7 dependency issues. Continuing on with using this package and following along with the quickstart, it seems the Authenticate request is broken, maybe something to do with pipelines.py?
`>>> client.authenticate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/qgenda/pipeline/pipelines.py", line 34, in decorated
    return method(client_obj, **params)
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/qgenda/pipeline/pipelines.py", line 54, in decorated
    response = method(client_self, *args, **kwargs)
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/qgenda/api/client.py", line 77, in authenticate
    response = requests.post(login_url, data=params, headers=headers)
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/jnorton/anaconda3/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'https=//api.qgenda.com/v2/login': No schema supplied. Perhaps you meant http://https=//api.qgenda.com/v2/login?`

**Comment by jjorissen52** [comment]
The below seems to indicate you supplied a bad url? it should be https://
not https=//

Invalid URL 'https=//api.qgenda.com/v2/login': No schema supplied. Perhaps
you meant

**Comment by lowjumpingfrog** [comment]
Thanks good now.
